pool: "Azure Pipelines"
trigger:
  branches:
    include:
    - main
variables:
- group: aws_credentials


steps:  
- task: TerraformCLI@0
  displayName: Terraform Init
  inputs:
    command: init
  env:
    AWS_ACCESS_KEY_ID: $(aws_access_key_id) 
    AWS_SECRET_ACCESS_KEY: $(aws_secret_access_key)
    AWS_DEFAULT_REGION : "us-east-1"
    TF_VAR_project_name: "task"
        
- task: TerraformCLI@0
  displayName: Terraform Plan
  inputs:
    command: plan
  env:
    AWS_ACCESS_KEY_ID: $(aws_access_key_id) 
    AWS_SECRET_ACCESS_KEY: $(aws_secret_access_key)
    AWS_DEFAULT_REGION : "us-east-1"
    TF_VAR_project_name: "task"
        
- task: TerraformCLI@0
  displayName: Terraform Apply
  inputs:
    command: apply
  env:
    AWS_ACCESS_KEY_ID: $(aws_access_key_id) 
    AWS_SECRET_ACCESS_KEY: $(aws_secret_access_key)
    AWS_DEFAULT_REGION : "us-east-1"
    TF_VAR_project_name: "task"
        
